version: "3.8"
services:
  postgres:
    image: postgres:alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
    - jschool-pg:/var/lib/postgresql/data
volumes:
  jschool-pg: